### ISSUE TITLE
Problems with update

### ISSUE THREAD

**Issue by Artimisia** [skandragon/thing#104]
The track coordinator for Martial track - #1 - thanks for the new locations, that is perfect. #2 - Cannot schedule an event for Friday, Aug. 6 at 11am-- the system seems to accept the time, but when the record is saved it reverts to 7am.  I tried to enter the 11am time-same thing happened, then tried using "override"-still reverts to 7am.

next item-When I try to generate a "free/allocated" report - a Red box appears that says "we're sorry but something went wrong".  I am so dependent on this report to know when class areas are empty - that I cannot schedule anything till it is fixed (sorry).

**Comment by Artimisia** [comment]
Another, just noticed problem --- any class I schedule (no matter day/time) shows up on the right day, but at 7am.

**Comment by skandragon** [comment]
I believe this has been fixed.  Ruby version is now locked to 2.1.6, the last version our older rails 3.2 supports.

**Comment by Artimisia** [comment]
Working great!  I have checked full/busy report and scheduled a number of
classes.
Thank you!  Great work!

In Service-
    Artis

THL Artimisia Lacebrayder
Pennsic University Registrar,Pennsic 44
mka: Artie Martin
e-mail: pennsicuregistrar@gmail.com
Phone: (586)296-7818(pre 9:00pm EST)
