### ISSUE TITLE
Thing problem

### ISSUE THREAD

**Issue by Galefridus** [skandragon/thing#105]
http://thing.pennsicuniversity.org/ seems to be having problems -- getting "web page not available" messages.

**Comment by skandragon** [comment]
Which page?

**Comment by Galefridus** [comment]
Go to this Pennsic War page:


http://www.pennsicwar.org/penn44/DEPTS/PENNU/


Under class listings is the following sentence:


The full class schedule <http://thing.pennsicuniversity.org/calendars> 
 is available at the online University Class scheduling site, Thing 
<http://thing.pennsicuniversity.org/> . Use the "Schedule/All Classes" 
menu to view printable/mobile device-friendly versions of the calendar.
The links for "full class schedule" 
(http://thing.pennsicuniversity.org/calendars) and for "Thing" 
(http://thing.pennsicuniversity.org/) both give "unable to connect" 
(Firefox) or "This webpage is not available" (Chrome) messages.
On Thu, Apr 16, 2015 at 12:25 PM, Michael Graff wrote:

Which page?


—
Reply to this email directly or view it on GitHub 
<https://github.com/skandragon/thing/issues/105#issuecomment-93777494> .

**Comment by skandragon** [comment]
Hmm, this works fine on my desktop, but not on my iPad, so there is a problem.  Looking into it now.

**Comment by skandragon** [comment]
It was working for IPv6 people, but not IPv4.  It should be working now.

I had to "flush cashes" on my Safari, but chrome should be more sane.
