### ISSUE TITLE
Cannot Generate a PDF Schedule

### ISSUE THREAD

**Issue by Artimisia** [skandragon/thing#106]
Just heard from a user (and confirmed) - I cannot generate either a "brief PDF" or a full PDF schedule.
The red "We're sorry, but something went wrong" message appears.
According to the user - this is a problem with the custom schedules too.

**Comment by skandragon** [comment]
Will fix shortly.

**Comment by Artimisia** [comment]
Thanks!

**Comment by skandragon** [comment]
Sorry that shortly took 19 days.  I think it works now.

I had to select Arial fonts (which will not be good for printing; we should use Arial for online looking but a serif font to print in the book as it's more readable at a smaller size) and I had to find ones which supported Unicode properly.

**Comment by Artimisia** [comment]
Thank you! I am headed out for a good bit of the day, but with a quick check it all seems to be working.  I will let the person know.
-Artis
