### ISSUE TITLE
Background on navbar is transparent, resulting in text floating on other text

### ISSUE THREAD

**Issue by maco** [skandragon/thing#108]
Screenshot shows text muddling where navbar overlaps text of page after scrolling
![screen shot 2015-07-10 at 12 20 33 pm](https://cloud.githubusercontent.com/assets/401264/8623200/1f5ed190-26fe-11e5-81b8-cb90dc3dc37c.png)

**Comment by skandragon** [comment]
Eww.  Well, that needs to be fixed.  What browser are you using?
